name: download_json

# run daily or manually
on:
  schedule:
    - cron: '11 1 * * *'
  workflow_dispatch:

# permission to write to the repository and manage actions
permissions:
  contents: write
  actions: write

jobs:
  # cancel the job if it takes more than 1 minute
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # clones repository into the github action runner
      - name: Checkout Repository
        uses: actions/checkout@v6

      # installs node.js 24 (Active LTS as of March 2026)
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # create a directory if it does not exist and run the daily script
      - name: Run Fetch Script
        run: |
          mkdir -p _dist
          node download_json.js

# peace iris - highly efficient
      - name: Deploy to Remote Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          # created and named in the GUI
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          # the source
          publish_dir: ./_dist
          # the destination
          external_repository: caaker/caaker.github.io
          publish_branch: main

















