name: download_json

on:
  schedule:
    - cron: '11 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository into the runner
        uses: actions/checkout@v6

      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run download_json.mjs
        run: node download_json.mjs

      # peace iris - highly efficient
      - name: Deploy to Remote Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          # created and named in the GUI
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          # the source
          publish_dir: ./_dist
          # the destination
          external_repository: caaker/caaker.github.io
          publish_branch: main

















