name: pack

# run this file on a push to main or manually
# this file has the net effect of running a build for frame-client and pushing the result to github pages
# regarding webpack, it is very efficient, if bundle.js does not change there is no change at the destination repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# a new run will cancel the previous run, this avoids collisions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository into the github runner
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install node 24 into the runner
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies in package-lock.json
        run: npm ci

      - name: Run build script
        run: npm run vite-dev

      # step 5
      - name: Deploy to remote repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          # created and named in the GUI
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          # the source
          publish_dir: ./_dist-vite
          # the destination
          external_repository: caaker/caaker.github.io
          publish_branch: main
    


