name: webpack

# run this file on a push to main or manually
# this file has the net effect of running webpack for frame-client

on:
  push:
    branches:
      - main
  workflow_dispatch:

# a new run will cancel the previous run, this avoids collisions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #clones into the github actions runner
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # installs node into runner
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # installs packages via package-lock.json
      - name: Install dependencies
        run: npm ci

      # runs build script defined in package.json
      - name: Run Webpack build
        run: npm run build-dev

      # pushes everthing in _dist to caaker.github.io
      - name: Push to caaker.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '_dist'
          destination-github-username: 'caaker'
          destination-repository-name: 'caaker.github.io'
          target-branch: 'main'
